### ISSUE TITLE
FEMA_fit fails when RandomEffects has just two elements

### ISSUE THREAD

**Issue by ofrei** [cmig-research-group/cmig_tools_deprecated#2] opened 2022-06-09 07:29 UTC
If one runs FEMA_Fit with  ``RandomEffects = {'A', 'E'}; `` the following error occurs:
```
Error using reshape
Size vector must have at least two elements.

Error in ndgrid_amd (line 13)
  x = reshape(x(:,ones(1,prod(s))),[length(x) s]); % Expand x

Error in FEMA_fit (line 171)
    sig2gridl = ndgrid_amd(repmat({binvals_edges(1:end-1)},[1 length(RandomEffects)-1]));

Error in FEMA_run_on_synthetic_data (line 66)
 beta_hat_perm, beta_se_perm, zmat_perm,     sig2tvec_perm, sig2mat_perm, logLikvec_perm] = FEMA_fit( ...
```

**Comment by dmysmith** [comment] 2023-01-20 20:28
Closing this issue (to our knowledge the issue is fixed).

**Closed as completed by dmysmith** 2023-01-20 20:28 UTC
